site_name: CiviCRM chatbot
theme: readthedocs
pages:
  - Introduction: index.md
  - Installation: installation.md
  - Getting started: getting-started.md
  - Conversation types: conversation-types.md
  - Starting conversations: starting-conversations.md
  - Chat and conversation tabs: chat-and-conversation-tabs.md
  - Chat services:
    - Configuring a chat service: service/configure.md
    - CiviSMS: service/civisms.md
    - Facebook messenger: service/facebook.md
    - Other services: service/other.md
  - CiviRules integration: civirules-integration.md
