<?php

use CRM_Chat_ExtensionUtil as E;

/**
 * Form controller class
 *
 * @see https://wiki.civicrm.org/confluence/display/CRMDOC/QuickForm+Reference
 */
class CRM_Chat_Form_Admin_Facebook extends CRM_Chat_Form_Good {

  function initFields(){

    $this->fields = [
      'chatbot_facebook_callback_url' => [
        'title' => 'Facebook callback URL',
        'help' => 'Facebook will send webhook updates to this callback URL. Configure your Facebook app webhook to use this URL.',
        'entity' => 'Setting',
        'field' => 'chatbot_facebook_callback_url',
        'freeze' => TRUE
      ],
      'chatbot_facebook_verify_token' => [
        'title' => 'Facebook verify token',
        'help' => 'This string is randomly generated by CiviCRM. You should configure your Facebook app webhook to use this token.  Update it to another value if you wish, or remove the value and save the form to generate another random token.',
        'description' => 'Facebook verify token',
        'entity' => 'Setting',
        'field' => 'chatbot_facebook_verify_token',
      ],
      'chatbot_facebook_app_secret' => [
        'title' => 'Facebook app secret',
        'help' => 'This secret is used by Facebook to authenticate messages sent from CiviCRM. Find it in your Facebook app, and add it here.',
        'entity' => 'Setting',
        'field' => 'chatbot_facebook_app_secret',
      ],
      'chatbot_facebook_page_access_token' => [
        'title' => 'Facebook page access token',
        'help' => 'This token is used by Facebook to authenticate messages sent from CiviCRM. Generate a Page access token in your Facebook app, and add it here.',
        'entity' => 'Setting',
        'field' => 'chatbot_facebook_page_access_token',
      ],
    ];

    if($this->entities['Setting']['before']['chatbot_facebook_verify_token'] == ''){
      $token = CRM_Chat_Utils::generateToken();
      $this->entities['Setting']['before']['chatbot_facebook_verify_token'] = $token;
      civicrm_api3('setting', 'create', ['chatbot_facebook_verify_token' => $token]);
    }


  }
  var $entities = [
    'Setting' => [
      'type' => 'Setting',
      'param' => 'id',
    ]
  ];

  function getDestination(){
    return CRM_Utils_System::url('civicrm/admin/chat/facebook/');
  }

  function getContext() {
    return CRM_Utils_System::url('civicrm/admin/chat/facebook/');
  }

  /**
   * Generates and saves a token on page load if one does not exist already
   */
  function setDefaultToken(){
  }

}
